#!/usr/bin/env sh

# Load Husky
. "$(dirname "$0")/_/husky.sh"

# Uncomment one of the following lines if your project has a testing script
# npm run test
# npm run test --coverage
# npm run test:cov
